### ISSUE TITLE
Potential issue

### ISSUE THREAD

**Issue by GrahamCampbell** [madewithlove/illuminate-psr-cache-bridge#1]
Just got the following in production:

```
Exception: DateInterval::__construct(): Unknown or bad format (PTS) in .../vendor/madewithlove/illuminate-psr-cache-bridge/src/Laravel/CacheItem.php:101
Stack trace:
#0 .../vendor/madewithlove/illuminate-psr-cache-bridge/src/Laravel/CacheItem.php(101): DateInterval->__construct('PTS')
#1 .../vendor/php-http/cache-plugin/src/CachePlugin.php(90): Madewithlove\IlluminatePsrCacheBridge\Laravel\CacheItem->expiresAfter(NULL)
#2 .../vendor/php-http/promise/src/FulfilledPromise.php(35): Http\Client\Common\Plugin\CachePlugin->Http\Client\Common\Plugin\{closure}(Object(GuzzleHttp\Psr7\Response))
#3 .../vendor/php-http/cache-plugin/src/CachePlugin.php(95): Http\Promise\FulfilledPromise->then(Object(Closure))
#4 .../vendor/php-http/client-common/src/PluginClient.php(155): Http\Client\Common\Plugin\CachePlugin-
```

I've not looked into this yet to determine if the other library is calling this one incorrectly, or if there's a bug here. Just giving you an early heads up.

**Comment by GrahamCampbell** [comment]
After investigation, it seems this is fixed by https://github.com/php-http/cache-plugin/pull/5.

**Comment by GrahamCampbell** [comment]
Actually, will need https://github.com/php-http/cache-plugin/pull/10 to fix too.

**Comment by GrahamCampbell** [comment]
Closing since the issue is not with this library. We probably could cast to an int though to be on the safe side.

**Comment by Nyholm** [comment]
Actually. There is a bug in this implementation. See https://github.com/php-http/cache-plugin/pull/10#issuecomment-236793275

I will update the integration test to cover this bug.
