### ISSUE TITLE
Any plan to add support for Laravel 6.0?

### ISSUE THREAD

**Issue by daveatpeta** [madewithlove/illuminate-psr-cache-bridge#17]

**Comment by GrahamCampbell** [comment]
Laravel 6 already ships with PSR-6 and PSR-16 support out of the box now.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/6.0/composer.json#L132
https://github.com/laravel/framework/blob/6.0/src/Illuminate/Cache/CacheServiceProvider.php#L18-L28
https://github.com/laravel/framework/blob/6.0/src/Illuminate/Foundation/Application.php#L1137-L1138

**Comment by pjordaan** [comment]
Hi, if I have a laravel package and I it requires this package because it needs a PSR Cache Interface, how do I make my library compatible with laravel 5.* and 6.*? The library could work in Laravel 6, even though it is not needed anymore.
If I say to composer that it requires laravel 6, then I can not require this package as it does not allow laravel 6. But if I want to make it usable in laravel 5 I need to require this package to make the library work.

**Comment by bertramakers** [comment]
The easiest way would be to make your Laravel package accept either Laravel 5.x and 6.x in Composer and `suggest` this package as a dependency for Laravel 5.x usage: https://getcomposer.org/doc/04-schema.md#suggest

Or you can maintain two versions of your package, one for Laravel 5.x and one for Laravel 6.x with slightly different Composer dependencies.

Note that `madewithlove/illuminate-psr-cache-bridge` provides a PSR-6 bridge, while Laravel 6 provides a PSR-16 cache with a PSR-6 adapter if needed. So you will need to depend on the PSR-6 cache interface in your package to make it work with both Laravel 5.x and Laravel 6.x.

**Comment by dinamic** [comment]
@GrahamCampbell the problem is that Laravel does not provide a package implementing `psr/cache-implementation`. Any attempts to have one working fail.

```
  Problem 1
    - cache/psr-6-doctrine-bridge 3.0.1 requires psr/cache-implementation ^1.0 -> no matching package found.
    - cache/psr-6-doctrine-bridge 3.0.0 requires psr/cache-implementation ^1.0 -> no matching package found.
    - Installation request for cache/psr-6-doctrine-bridge ^3.0 -> satisfiable by cache/psr-6-doctrine-bridge[3.0.0, 3.0.1].
```

**Comment by dinamic** [comment]
A viable workaround for this could be to use `symfony/cache`. Here's the documentation on providing a PSR-6 cache adapter that's going to use Laravel's PSR-16 one:
- https://symfony.com/doc/current/components/cache/psr6_psr16_adapters.html#using-a-psr-16-cache-object-as-a-psr-6-cache

To provide PSR-6 compatibility to the application I work on, I've used the following in a service provider:

```
    private function registerSymfonyCache(): void
    {
        $this->app->singleton(Symfony\Component\Cache\Adapter\Psr16Adapter::class, static function (Container $container): Symfony\Component\Cache\Adapter\Psr16Adapter {
            return new Symfony\Component\Cache\Adapter\Psr16Adapter(
                $container->make(Psr\SimpleCache\CacheInterface::class)
            );
        });

        $this->app->singleton(Symfony\Component\Cache\Adapter\Psr16Adapter::class, Psr\Cache\CacheItemPoolInterface::class);
    }
```

**Comment by bertramakers** [comment]
@dinamic If I'm not mistaken Laravel 6 already provides a PSR-6 service IF you add `symfony/cache` like you mentioned: https://github.com/laravel/framework/blob/6.x/src/Illuminate/Cache/CacheServiceProvider.php#L26-L28

**Comment by dinamic** [comment]
Good find, @bertramakers.
I just wanted to be explicit with the implementation of the PSR-6 interface.

**Comment by GrahamCampbell** [comment]
Yes, I added this to Laravel. ;)

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/commit/2926722504ec61669ba7c8e2c09cf96929557401
